docker:
  - image: circleci/buildpack-deps
shell: /usr/bin/env bash -euo pipefail -c
steps:
  - checkout
  - setup_remote_docker
  - run:
      name: Build Docker Image if Necessary
      command: |
        IMAGE_TAG=$(cat website/Dockerfile website/package-lock.json | sha256sum | awk '{print $1;}')
        if ! curl https://hub.docker.com/v2/repositories/hashicorp/nomad-website/tags/$IMAGE_TAG -fsL > /dev/null; then
          cd website/
          docker build -t hashicorp/nomad-website:$IMAGE_TAG .
          docker tag hashicorp/nomad-website:$IMAGE_TAG hashicorp/nomad-website:latest
          docker login -u $WEBSITE_DOCKER_USER -p $WEBSITE_DOCKER_PASS
          docker push hashicorp/nomad-website
        else
          echo "Not building a new website docker image - branch is not master and/or dependencies have not changed."
        fi
